services:
  cache-proxy:
    image: openresty/openresty:alpine
    container_name: shadertoy-cache-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cached_shaders:/etc/nginx/cached_shaders:ro
      - ./cache:/etc/nginx/cache
    ports:
      - "8888:80"
